version: "3.8"
services:
    onedrive:
        container_name: onedrive
        image: driveone/onedrive:edge
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=${PUID}
            - ONEDRIVE_GID=${PGID}
        volumes: 
            - ${HOME}/Configuration/OneDrive:/onedrive/conf
            - ${HOME}/OneDrive:/onedrive/data